services:
  akavo_entity_db:
    image: mongo
    container_name: arkavo_db
    ports:
      - "27017:27017"
    networks:
      - arkavo_network
    volumes:
      - mongo_data:/data/db
    restart: always

networks:
  arkavo_network:
    driver: bridge

volumes:
  mongo_data:
