version: '3'
services:
  akavo_accessor_service:
    build: .
    container_name: arkavo_entity
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://arkavo_entity_db:27017/your_database_name
    networks:
      - akavo_network
    restart: always
