networks:
  default:
    name: opentdf_platform
services:
  opentdf:
    container_name: opentdf
    image: julianfl0w/opentdf:1.0
    restart: always
    environment:
      KEYCLOAK_BASE_URL: ${KEYCLOAK_SERVER_URL}
    ports:
      - "8080:8080"
    command: start
    volumes:
      - ./opentdf-dev.yaml:/app/opentdf.yaml
      - ${PWD}:/keys
      - ./kas-cert.pem:/app/kas-cert.pem
      - ./kas-ec-cert.pem:/app/kas-ec-cert.pem
      - ./kas-private.pem:/app/kas-private.pem
      - ./kas-ec-private.pem:/app/kas-ec-private.pem
    healthcheck:
      test: ["CMD-SHELL", "curl -sf ${KEYCLOAK_SERVER_URL} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
